runs:
  using: "composite"
  steps:
    - name: Set up Java
      uses: actions/setup-java@v3
      with:
        distribution: 'temurin'
        java-version: '21'
  
    - name: Set up Clojure and Babashka
      uses: DeLaGuardo/setup-clojure@ada62bb3282a01a296659d48378b812b8e097360 # Pinned: 13.2
      with:
        # https://clojure.org/releases/tools
        cli: '1.12.0.1530'
        # https://github.com/babashka/babashka/releases
        bb: '1.12.197'

    - name: Cache clojure dependencies
      uses: actions/cache@v3
      with:
        path: |
          ~/.m2/repository
          ~/.gitlibs
          ~/.deps.clj
        key: cljdeps-${{ hashFiles('deps.edn') }}
        restore-keys: cljdeps-
